/**This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

package com.fico.dmp.services.damserviceimplservice.services;
import com.fico.dmp.services.damserviceimplservice.*;
import java.util.List;

import com.wavemaker.runtime.soap.util.SoapSettingsResolver;
import com.wavemaker.runtime.soap.EnvSoapServiceSettings;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import javax.xml.ws.BindingProvider;



@Service
public class DAMServiceImplServiceService{

    @Autowired
    @Qualifier("DAMServiceImplServiceSoapServiceSettings")
    private EnvSoapServiceSettings envSoapServiceSettings;


	public GetBusinessSearchDataResponse getBusinessSearchData(  com.fico.dmp.services.damserviceimplservice.GetBusinessSearchData parameters )
	          {
 	    DAMServiceImplService damserviceimplservice = new DAMServiceImplService();
 DAMService damservice = damserviceimplservice.getDAMServiceImplPort();
 SoapSettingsResolver.setBindingProperties((BindingProvider)damservice, envSoapServiceSettings.getSettings());
 return damservice.getBusinessSearchData(parameters );
	}

	public GetBusinessReportDataResponse getBusinessReportData(  com.fico.dmp.services.damserviceimplservice.GetBusinessReportData parameters )
	          {
 	    DAMServiceImplService damserviceimplservice = new DAMServiceImplService();
 DAMService damservice = damserviceimplservice.getDAMServiceImplPort();
 SoapSettingsResolver.setBindingProperties((BindingProvider)damservice, envSoapServiceSettings.getSettings());
 return damservice.getBusinessReportData(parameters );
	}

	public GetBusinessSearchReportDataResponse getBusinessSearchReportData(  com.fico.dmp.services.damserviceimplservice.GetBusinessSearchReportData parameters )
	          {
 	    DAMServiceImplService damserviceimplservice = new DAMServiceImplService();
 DAMService damservice = damserviceimplservice.getDAMServiceImplPort();
 SoapSettingsResolver.setBindingProperties((BindingProvider)damservice, envSoapServiceSettings.getSettings());
 return damservice.getBusinessSearchReportData(parameters );
	}

	public GetConsumerReportDataResponse getConsumerReportData(  com.fico.dmp.services.damserviceimplservice.GetConsumerReportData parameters )
	          {
 	    DAMServiceImplService damserviceimplservice = new DAMServiceImplService();
 DAMService damservice = damserviceimplservice.getDAMServiceImplPort();
 SoapSettingsResolver.setBindingProperties((BindingProvider)damservice, envSoapServiceSettings.getSettings());
 return damservice.getConsumerReportData(parameters );
	}
}
