/*Copyright (c) 2019-2020 fico.com All Rights Reserved.
 This software is the confidential and proprietary information of fico.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with fico.com*/
package com.fico.dmp.dmpprofiles;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FawbPropertySource generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`FAWB_PROPERTY_SOURCE`")
public class FawbPropertySource implements Serializable {

    private Integer id;
    private String propertyKey;
    private String propertyValue;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`PROPERTY_KEY`", nullable = true, length = 255)
    public String getPropertyKey() {
        return this.propertyKey;
    }

    public void setPropertyKey(String propertyKey) {
        this.propertyKey = propertyKey;
    }

    @Column(name = "`PROPERTY_VALUE`", nullable = true, length = 255)
    public String getPropertyValue() {
        return this.propertyValue;
    }

    public void setPropertyValue(String propertyValue) {
        this.propertyValue = propertyValue;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof FawbPropertySource)) return false;
        final FawbPropertySource fawbPropertySource = (FawbPropertySource) o;
        return Objects.equals(getId(), fawbPropertySource.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}