-- MIGRATION SCRIPT
-- Database Type: DBType{type='mysql', urlScheme='jdbc:', dialect='org.hibernate.dialect.MySQLDialect', driverClass='com.mysql.jdbc.Driver'}
-- App Name: projectpreview_dp
-- Database: dmpprofiles
-- Created At: 03-Apr-2020 09:22:50.UTC
-- Script Version: 1.1
-- -----------------------------------------------------------------
-- USER SQL SCRIPT