/**
 *This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.
 */
package com.fico.dmp.services.damserviceimplservice.controller;

import com.fico.dmp.services.damserviceimplservice.services.DAMServiceImplServiceService;
import com.fico.dmp.services.damserviceimplservice.GetBusinessReportData;
import com.fico.dmp.services.damserviceimplservice.GetBusinessReportDataResponse;
import com.fico.dmp.services.damserviceimplservice.GetBusinessSearchData;
import com.fico.dmp.services.damserviceimplservice.GetBusinessSearchDataResponse;
import com.fico.dmp.services.damserviceimplservice.GetBusinessSearchReportData;
import com.fico.dmp.services.damserviceimplservice.GetBusinessSearchReportDataResponse;
import com.fico.dmp.services.damserviceimplservice.GetConsumerReportData;
import com.fico.dmp.services.damserviceimplservice.GetConsumerReportDataResponse;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.MediaType;
import org.springframework.beans.factory.annotation.Autowired;

@RestController
@RequestMapping(value = "/dAMServiceImplServiceController")
@com.wavemaker.runtime.security.xss.XssDisable
public class DAMServiceImplServiceController {

    @Autowired
    private DAMServiceImplServiceService dAMServiceImplServiceService;

    @RequestMapping(value = "/businessReportData", method = RequestMethod.POST)
    public GetBusinessReportDataResponse getBusinessReportData(@RequestBody GetBusinessReportData parameters) {
        return dAMServiceImplServiceService.getBusinessReportData(parameters);
    }

    @RequestMapping(value = "/businessSearchData", method = RequestMethod.POST)
    public GetBusinessSearchDataResponse getBusinessSearchData(@RequestBody GetBusinessSearchData parameters) {
        return dAMServiceImplServiceService.getBusinessSearchData(parameters);
    }

    @RequestMapping(value = "/businessSearchReportData", method = RequestMethod.POST)
    public GetBusinessSearchReportDataResponse getBusinessSearchReportData(@RequestBody GetBusinessSearchReportData parameters) {
        return dAMServiceImplServiceService.getBusinessSearchReportData(parameters);
    }

    @RequestMapping(value = "/consumerReportData", method = RequestMethod.POST)
    public GetConsumerReportDataResponse getConsumerReportData(@RequestBody GetConsumerReportData parameters) {
        return dAMServiceImplServiceService.getConsumerReportData(parameters);
    }
}
