/*Copyright (c) 2019-2020 fico.com All Rights Reserved.
 This software is the confidential and proprietary information of fico.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with fico.com*/
package com.fico.dmp.services.damserviceimplservice;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2020-04-01T06:06:38.423Z
 * Generated source version: 3.2.6
 *
 */
@WebServiceClient(name = "DAMServiceImplService",
                  wsdlLocation = "DAMServiceImplService.wsdl",
                  targetNamespace = "http://main.dam.om.fico.com/")
public class DAMServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://main.dam.om.fico.com/", "DAMServiceImplService");
    public final static QName DAMServiceImplPort = new QName("http://main.dam.om.fico.com/", "DAMServiceImplPort");
    static {
        URL url = DAMServiceImplService.class.getResource("DAMServiceImplService.wsdl");
        if (url == null) {
            url = DAMServiceImplService.class.getClassLoader().getResource("DAMServiceImplService.wsdl");
        }
        if (url == null) {
            java.util.logging.Logger.getLogger(DAMServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "DAMServiceImplService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DAMServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DAMServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DAMServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public DAMServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DAMServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DAMServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns DAMService
     */
    @WebEndpoint(name = "DAMServiceImplPort")
    public DAMService getDAMServiceImplPort() {
        return super.getPort(DAMServiceImplPort, DAMService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DAMService
     */
    @WebEndpoint(name = "DAMServiceImplPort")
    public DAMService getDAMServiceImplPort(WebServiceFeature... features) {
        return super.getPort(DAMServiceImplPort, DAMService.class, features);
    }

}