/*Copyright (c) 2019-2020 fico.com All Rights Reserved.
 This software is the confidential and proprietary information of fico.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with fico.com*/
package com.fico.dmp.services.damserviceimplservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2020-04-03T09:57:33.638Z
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://dam.om.fico.com/", name = "DAMService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DAMService {

    @WebMethod
    @Action(input = "http://dam.om.fico.com/DAMService/getBusinessSearchDataRequest", output = "http://dam.om.fico.com/DAMService/getBusinessSearchDataResponse")
    @WebResult(name = "getBusinessSearchDataResponse", targetNamespace = "http://dam.om.fico.com/", partName = "parameters")
    public GetBusinessSearchDataResponse getBusinessSearchData(
        @WebParam(partName = "parameters", name = "getBusinessSearchData", targetNamespace = "http://dam.om.fico.com/")
        GetBusinessSearchData parameters
    );

    @WebMethod
    @Action(input = "http://dam.om.fico.com/DAMService/getBusinessReportDataRequest", output = "http://dam.om.fico.com/DAMService/getBusinessReportDataResponse")
    @WebResult(name = "getBusinessReportDataResponse", targetNamespace = "http://dam.om.fico.com/", partName = "parameters")
    public GetBusinessReportDataResponse getBusinessReportData(
        @WebParam(partName = "parameters", name = "getBusinessReportData", targetNamespace = "http://dam.om.fico.com/")
        GetBusinessReportData parameters
    );

    @WebMethod
    @Action(input = "http://dam.om.fico.com/DAMService/getBusinessSearchReportDataRequest", output = "http://dam.om.fico.com/DAMService/getBusinessSearchReportDataResponse")
    @WebResult(name = "getBusinessSearchReportDataResponse", targetNamespace = "http://dam.om.fico.com/", partName = "parameters")
    public GetBusinessSearchReportDataResponse getBusinessSearchReportData(
        @WebParam(partName = "parameters", name = "getBusinessSearchReportData", targetNamespace = "http://dam.om.fico.com/")
        GetBusinessSearchReportData parameters
    );

    @WebMethod
    @Action(input = "http://dam.om.fico.com/DAMService/getConsumerReportDataRequest", output = "http://dam.om.fico.com/DAMService/getConsumerReportDataResponse")
    @WebResult(name = "getConsumerReportDataResponse", targetNamespace = "http://dam.om.fico.com/", partName = "parameters")
    public GetConsumerReportDataResponse getConsumerReportData(
        @WebParam(partName = "parameters", name = "getConsumerReportData", targetNamespace = "http://dam.om.fico.com/")
        GetConsumerReportData parameters
    );
}