/*Copyright (c) 2019-2020 fico.com All Rights Reserved.
 This software is the confidential and proprietary information of fico.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with fico.com*/
package com.fico.dmp.services.damserviceimplservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2020-04-03T09:57:33.622Z
 * Generated source version: 3.2.6
 *
 */
public final class DAMService_DAMServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://main.dam.om.fico.com/", "DAMServiceImplService");

    private DAMService_DAMServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = DAMServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        DAMServiceImplService ss = new DAMServiceImplService(wsdlURL, SERVICE_NAME);
        DAMService port = ss.getDAMServiceImplPort();

        {
        System.out.println("Invoking getBusinessSearchData...");
        com.fico.dmp.services.damserviceimplservice.GetBusinessSearchData _getBusinessSearchData_parameters = null;
        com.fico.dmp.services.damserviceimplservice.GetBusinessSearchDataResponse _getBusinessSearchData__return = port.getBusinessSearchData(_getBusinessSearchData_parameters);
        System.out.println("getBusinessSearchData.result=" + _getBusinessSearchData__return);


        }
        {
        System.out.println("Invoking getBusinessReportData...");
        com.fico.dmp.services.damserviceimplservice.GetBusinessReportData _getBusinessReportData_parameters = null;
        com.fico.dmp.services.damserviceimplservice.GetBusinessReportDataResponse _getBusinessReportData__return = port.getBusinessReportData(_getBusinessReportData_parameters);
        System.out.println("getBusinessReportData.result=" + _getBusinessReportData__return);


        }
        {
        System.out.println("Invoking getBusinessSearchReportData...");
        com.fico.dmp.services.damserviceimplservice.GetBusinessSearchReportData _getBusinessSearchReportData_parameters = null;
        com.fico.dmp.services.damserviceimplservice.GetBusinessSearchReportDataResponse _getBusinessSearchReportData__return = port.getBusinessSearchReportData(_getBusinessSearchReportData_parameters);
        System.out.println("getBusinessSearchReportData.result=" + _getBusinessSearchReportData__return);


        }
        {
        System.out.println("Invoking getConsumerReportData...");
        com.fico.dmp.services.damserviceimplservice.GetConsumerReportData _getConsumerReportData_parameters = null;
        com.fico.dmp.services.damserviceimplservice.GetConsumerReportDataResponse _getConsumerReportData__return = port.getConsumerReportData(_getConsumerReportData_parameters);
        System.out.println("getConsumerReportData.result=" + _getConsumerReportData__return);


        }

        System.exit(0);
    }

}